# Generated by Django 4.1.5 on 2023-08-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_description_contact_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='description',
        ),
    ]
