# Generated by Django 4.1.5 on 2023-08-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('number', models.IntegerField(max_length=12)),
                ('collage_name', models.CharField(max_length=70)),
                ('collage_REG_NO', models.CharField(max_length=70)),
                ('offerstatus', models.CharField(max_length=70)),
                ('startdate', models.CharField(max_length=80)),
                ('enddate', models.CharField(max_length=90)),
                ('proj_report', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
