# Generated by Django 4.1.5 on 2023-08-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_internship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='number',
            field=models.IntegerField(),
        ),
    ]
